{% set name = "birka" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/birka-{{ version }}.tar.gz
  sha256: d10d57232a3ab71d3dfa763a626d33501aad19b91af0d8dfa333607155cec074

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - birka = birka:main
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10,<3.12
    - aicsimageio
    - pandas
    - qtpy
  run_constrained:
    - lxml <5

test:
  imports:
    - birka
  commands:
    - pip check
  requires:
    - pip
    - pyside6

about:
  home: https://github.com/BIIFSweden/birka
  summary: A tool for bioimage data validation and archival
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jwindhager
